export const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST'
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
export const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE'

export const INSERT_TODO_REQUEST = 'INSERT_TODO_REQUEST'
export const INSERT_TODO_SUCCESS = 'INSERT_TODO_SUCCESS'
export const INSERT_TODO_FAILURE = 'INSERT_TODO_FAILURE'
