export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE'

export const FETCH_REGISTRATION_REQUEST = 'FETCH_REGISTRATION_REQUEST'
export const FETCH_REGISTRATION_SUCCESS = 'FETCH_REGISTRATION_SUCCESS'
export const FETCH_REGISTRATION_FAILURE = 'FETCH_REGISTRATION_FAILURE'

export const LOGOUT = 'LOGOUT'


